### Get all posts
GET http://localhost:3000/api/post
Content-Type: application/json

### Get post by id
GET http://localhost:3000/api/post/675073bc49f76c9c0a7ab99c

### Create post
POST http://localhost:3000/api/post
Content-Type: application/json

{
    "title": "Post 1",
    "content": "Content 1",
    "owner": "675016b349f76c9c0a7ab99a"
}

### Update post
PUT http://localhost:3000/api/post/675073bc49f76c9c0a7ab99c
Content-Type: application/json

{
    "title": "Post 1",
    "content": "updated Content!",
    "owner": "675016b349f76c9c0a7ab99a"
}

### Get post by sender
GET http://localhost:3000/api/post?sender=675016b349f76c9c0a7ab99a

### Get comment by id
GET http://localhost:3000/api/comment/6766baf03a9f5c7b26fc0aef

### Create comment
POST http://localhost:3000/api/comment
Content-Type: application/json

{
    "message": "amazinggg!!",
    "userId": "675016b349f76c9c0a7ab99a",
    "postId": "675073bc49f76c9c0a7ab99c"
}

### Update comment
PUT http://localhost:3000/api/comment/6769b1895938d243f1752c5d
Content-Type: application/json

{
    "message": "updated comment!"
}


### Get post's comments
GET http://localhost:3000/api/comment/675073bc49f76c9c0a7ab99c

### Delete comment
DELETE http://localhost:3000/api/comment/6769b1b85938d243f1752c5f